MEMORY
{
  RAM : ORIGIN = 0x80000000, LENGTH = 960K
  STACK : ORIGIN = 0x800F0000, LENGTH = 64K
}

REGION_ALIAS("REGION_TEXT", RAM);
REGION_ALIAS("REGION_RODATA", RAM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", STACK);

/* riscv-rt exposes the bottom of its reserved stack as __estack. */
_stack_end = __estack;
