use core::{mem::MaybeUninit, ptr};

use crate::{Matrix, Real, Zero};

use super::ldlt::StaticCscLdlt;
use super::{
    SparseCholeskyError, StaticCscMatrix, StaticCscOrdering, StaticCscPattern, StaticCscPermutation,
};

#[inline]
unsafe fn zero_storage<T>(output: *mut T) {
    // SAFETY: callers use this only for integer, boolean, or byte-zero-initializable storage.
    unsafe { ptr::write_bytes(output.cast::<u8>(), 0, core::mem::size_of::<T>()) };
}

/// Symbolic pattern for a fixed-capacity simplicial sparse Cholesky factor.
///
/// The pattern includes the lower-triangular fill generated by the input
/// structure. It can be retained and reused while numeric values change.
///
/// Analysis is the symbolic phase: it validates the lower CSC structure and
/// reserves enough factor capacity for fill. Call [`Self::factor`] for the
/// first numeric factorization, then [`StaticCscCholesky::recompute`] (or
/// [`Self::factor_ordered`] when using [`Self::prepare_ordered`]) for later
/// iterations with the same structure.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StaticCscCholeskyPattern<const N: usize, const MAX_L_NNZ: usize> {
    lower: StaticCscPattern<N, N, MAX_L_NNZ>,
    ordering: StaticCscOrdering<N>,
    update_starts: [usize; N],
    update_indices: [u32; MAX_L_NNZ],
    update_columns: [u32; MAX_L_NNZ],
    update_row_starts: [u32; MAX_L_NNZ],
    update_contiguous: [bool; MAX_L_NNZ],
    update_nnz: usize,
    parent: [u32; N],
    aggregate_update_starts: [u32; N],
    aggregate_update_indices: [u32; MAX_L_NNZ],
    aggregate_update_columns: [u32; MAX_L_NNZ],
    aggregate_update_nnz: usize,
    numeric_pattern_starts: [u32; N],
    numeric_pattern_columns: [u32; MAX_L_NNZ],
    numeric_pattern_nnz: usize,
    input_diagonal_indices: [u32; N],
    factor_row_starts: [u32; N],
    factor_contiguous: [bool; N],
}

impl<const N: usize, const MAX_L_NNZ: usize> StaticCscCholeskyPattern<N, MAX_L_NNZ> {
    /// Returns the exact inline storage footprint of this symbolic factor.
    #[inline]
    pub const fn storage_bytes() -> usize {
        core::mem::size_of::<Self>()
    }

    pub(crate) fn from_lower_with_ordering(
        lower: StaticCscPattern<N, N, MAX_L_NNZ>,
        ordering: StaticCscOrdering<N>,
    ) -> Self {
        let mut output = MaybeUninit::uninit();
        // SAFETY: `from_lower_with_ordering_into` initializes every field before returning.
        unsafe {
            Self::from_lower_with_ordering_into(&lower, ordering, &mut output);
            output.assume_init()
        }
    }

    fn from_lower_with_ordering_into(
        lower: &StaticCscPattern<N, N, MAX_L_NNZ>,
        ordering: StaticCscOrdering<N>,
        output: &mut MaybeUninit<Self>,
    ) {
        let output = output.as_mut_ptr();
        // Initialize the capacity-sized output arrays before using them as the symbolic scratch
        // buffers. This keeps the analysis from creating duplicate arrays on the caller's stack.
        unsafe {
            ptr::addr_of_mut!((*output).lower).write(*lower);
            ptr::addr_of_mut!((*output).ordering).write(ordering);
            zero_storage(ptr::addr_of_mut!((*output).update_indices));
            zero_storage(ptr::addr_of_mut!((*output).update_columns));
            zero_storage(ptr::addr_of_mut!((*output).update_row_starts));
            zero_storage(ptr::addr_of_mut!((*output).update_contiguous));
            zero_storage(ptr::addr_of_mut!((*output).aggregate_update_starts));
            zero_storage(ptr::addr_of_mut!((*output).aggregate_update_indices));
            zero_storage(ptr::addr_of_mut!((*output).aggregate_update_columns));
            zero_storage(ptr::addr_of_mut!((*output).numeric_pattern_starts));
            zero_storage(ptr::addr_of_mut!((*output).numeric_pattern_columns));
            for value in &mut (*output).input_diagonal_indices {
                *value = u32::MAX;
            }
        }
        let mut update_counts = [0usize; N];
        for column in 0..N {
            let start = unsafe { (*output).lower.column_starts()[column] as usize };
            let end = unsafe { (*output).lower.column_end(column).unwrap_or(lower.nnz()) };
            for index in (start + 1)..end {
                let row = unsafe { (*output).lower.row_indices()[index] as usize };
                update_counts[row] += 1;
            }
        }

        let mut update_starts = [0usize; N];
        let mut update_nnz = 0;
        for row in 0..N {
            update_starts[row] = update_nnz;
            update_nnz += update_counts[row];
        }
        let mut update_cursor = update_starts;
        let mut parent = [u32::MAX; N];
        let mut factor_row_starts = [0u32; N];
        let mut factor_contiguous = [false; N];
        for column in 0..N {
            let start = unsafe { (*output).lower.column_starts()[column] as usize };
            let end = unsafe { (*output).lower.column_end(column).unwrap_or(lower.nnz()) };
            if start + 1 < end {
                parent[column] = unsafe { (*output).lower.row_indices()[start + 1] };
                let first_row = unsafe { (*output).lower.row_indices()[start + 1] as usize };
                factor_row_starts[column] = first_row as u32;
                factor_contiguous[column] =
                    unsafe { &(*output).lower.row_indices()[start + 1..end] }
                        .iter()
                        .enumerate()
                        .all(|(offset, &candidate)| candidate == (first_row + offset) as u32);
            }
            for index in (start + 1)..end {
                let row = unsafe { (*output).lower.row_indices()[index] as usize };
                let position = update_cursor[row];
                unsafe {
                    (*output).update_indices[position] = index as u32;
                    (*output).update_columns[position] = column as u32;
                }
                let first_row = unsafe { (*output).lower.row_indices()[index] as usize };
                let contiguous = unsafe { &(*output).lower.row_indices()[index..end] }
                    .iter()
                    .enumerate()
                    .all(|(offset, &candidate)| candidate == (first_row + offset) as u32);
                unsafe {
                    (*output).update_row_starts[position] = first_row as u32;
                    (*output).update_contiguous[position] = contiguous;
                }
                update_cursor[row] += 1;
            }
        }

        // SAFETY: the capacity-sized arrays were initialized above and the remaining scalar/size-N
        // fields are initialized exactly once before the output is exposed as `Self`.
        unsafe {
            ptr::addr_of_mut!((*output).update_starts).write(update_starts);
            ptr::addr_of_mut!((*output).update_nnz).write(update_nnz);
            ptr::addr_of_mut!((*output).parent).write(parent);
            ptr::addr_of_mut!((*output).aggregate_update_nnz).write(0);
            ptr::addr_of_mut!((*output).numeric_pattern_nnz).write(0);
            ptr::addr_of_mut!((*output).factor_row_starts).write(factor_row_starts);
            ptr::addr_of_mut!((*output).factor_contiguous).write(factor_contiguous);
        }
    }

    fn with_input_pattern_mut<const MAX_A_NNZ: usize, T: Copy + Zero>(
        &mut self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) {
        let matrix_pattern = matrix.pattern();
        for column in 0..N {
            self.input_diagonal_indices[column] = matrix_pattern
                .entry_index(column, column)
                .map(|index| index as u32)
                .unwrap_or(u32::MAX);
        }

        let mut aggregate_update_nnz = 0;
        for row in 0..N {
            let start = self.update_starts[row];
            let end = if row + 1 < N {
                self.update_starts[row + 1]
            } else {
                self.update_nnz
            };
            self.aggregate_update_starts[row] = aggregate_update_nnz as u32;
            for update in start..end {
                let factor_index = self.update_indices[update] as usize;
                let column = self.update_columns[update] as usize;
                let factor_row = self.lower.row_indices()[factor_index] as usize;
                if let Some(source_index) = matrix_pattern.entry_index(factor_row, column) {
                    self.aggregate_update_indices[aggregate_update_nnz] = source_index as u32;
                    self.aggregate_update_columns[aggregate_update_nnz] = column as u32;
                    aggregate_update_nnz += 1;
                }
            }
        }
        self.aggregate_update_nnz = aggregate_update_nnz;

        let mut numeric_pattern_nnz = 0;
        if N != 0 && self.input_diagonal_indices[0] != u32::MAX {
            let mut visited = [usize::MAX; N];
            let mut column_pattern = [0usize; N];
            for column in 0..N {
                self.numeric_pattern_starts[column] = numeric_pattern_nnz as u32;
                visited[column] = column;
                let mut top = N;
                let update_start = self.aggregate_update_starts[column] as usize;
                let update_end = if column + 1 < N {
                    self.aggregate_update_starts[column + 1] as usize
                } else {
                    self.aggregate_update_nnz
                };
                for update in update_start..update_end {
                    let mut node = self.aggregate_update_columns[update] as usize;
                    let mut depth = 0;
                    while visited[node] != column {
                        column_pattern[depth] = node;
                        visited[node] = column;
                        node = self.parent[node] as usize;
                        depth += 1;
                    }
                    while depth > 0 {
                        top -= 1;
                        depth -= 1;
                        column_pattern[top] = column_pattern[depth];
                    }
                }
                for &previous in &column_pattern[top..N] {
                    debug_assert!(numeric_pattern_nnz < MAX_L_NNZ);
                    self.numeric_pattern_columns[numeric_pattern_nnz] = previous as u32;
                    numeric_pattern_nnz += 1;
                }
            }
        }
        self.numeric_pattern_nnz = numeric_pattern_nnz;
    }

    /// Analyzes the lower-triangular structure of a symmetric CSC matrix.
    ///
    /// The analysis is conservative: entries that may cancel numerically are
    /// still retained in the factor pattern, which makes the pattern reusable
    /// across iterations with different values.
    #[inline]
    pub fn analyze<const MAX_A_NNZ: usize, T: Real + Copy + Zero>(
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<Self, SparseCholeskyError> {
        let mut output = MaybeUninit::uninit();
        Self::analyze_natural_into(matrix, &mut output)?;
        // SAFETY: `analyze_natural_into` initializes every field before returning `Ok`.
        return Ok(unsafe { output.assume_init() });
    }

    fn analyze_natural_into<const MAX_A_NNZ: usize, T: Real + Copy + Zero>(
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        output: &mut MaybeUninit<Self>,
    ) -> Result<(), SparseCholeskyError> {
        validate_symmetric_structure(matrix)?;
        if MAX_A_NNZ > MAX_L_NNZ {
            return Self::analyze_natural_with_local_scratch(matrix, output);
        }
        let output_ptr = output.as_mut_ptr();
        // Reuse the destination's capacity-sized arrays for symbolic adjacency and factor row
        // construction. The factor capacity must cover the input capacity for this path.
        unsafe {
            zero_storage(ptr::addr_of_mut!((*output_ptr).lower));
            zero_storage(ptr::addr_of_mut!((*output_ptr).update_indices));
        }
        // Build the upper-column adjacency implied by the stored lower
        // triangle.  For a lower entry (row, column), the corresponding
        // upper entry is visited from column `row` with predecessor `column`.
        let mut row_counts = [0usize; N];
        for column in 0..N {
            let start = matrix.column_starts()[column] as usize;
            let end = matrix.column_end(column).unwrap_or(matrix.nnz());
            for index in start..end {
                let row = matrix.row_indices()[index] as usize;
                if row > column {
                    row_counts[row] += 1;
                }
            }
        }
        let mut row_starts = [0usize; N];
        for row in 1..N {
            row_starts[row] = row_starts[row - 1] + row_counts[row - 1];
        }
        let mut row_cursor = row_starts;
        for column in 0..N {
            let start = matrix.column_starts()[column] as usize;
            let end = matrix.column_end(column).unwrap_or(matrix.nnz());
            for index in start..end {
                let row = matrix.row_indices()[index] as usize;
                if row > column {
                    unsafe { (*output_ptr).update_indices[row_cursor[row]] = column as u32 };
                    row_cursor[row] += 1;
                }
            }
        }

        // Compute the elimination tree and the exact number of off-diagonal
        // entries in each factor column.  This is the same reachability
        // algorithm used by the C++ sparse solver and avoids an O(N²) dense
        // reachability workspace for large bundle-adjustment systems.
        let mut visited = [usize::MAX; N];
        let mut parent = [usize::MAX; N];
        let mut column_counts = [1usize; N];
        for column in 0..N {
            visited[column] = column;
            let start = row_starts[column];
            let end = if column + 1 < N {
                row_starts[column + 1]
            } else {
                row_starts[column] + row_counts[column]
            };
            for &upper_column in unsafe { &(&(*output_ptr).update_indices)[start..end] } {
                let mut node = upper_column as usize;
                while visited[node] != column {
                    if parent[node] == usize::MAX {
                        parent[node] = column;
                    }
                    column_counts[node] += 1;
                    visited[node] = column;
                    node = parent[node];
                }
            }
        }

        let mut column_starts = [0usize; N];
        for column in 1..N {
            column_starts[column] = column_starts[column - 1] + column_counts[column - 1];
        }
        let total_nnz = if N == 0 {
            0
        } else {
            column_starts[N - 1] + column_counts[N - 1]
        };
        if total_nnz > MAX_L_NNZ {
            return Err(SparseCholeskyError::CapacityExceeded);
        }

        for column in 0..N {
            unsafe { (*output_ptr).lower.row_indices[column_starts[column]] = column as u32 };
        }
        let mut cursors = column_starts;
        for cursor in &mut cursors {
            *cursor += 1;
        }
        visited = [usize::MAX; N];
        for column in 0..N {
            visited[column] = column;
            let start = row_starts[column];
            let end = if column + 1 < N {
                row_starts[column + 1]
            } else {
                row_starts[column] + row_counts[column]
            };
            for &upper_column in unsafe { &(&(*output_ptr).update_indices)[start..end] } {
                let mut node = upper_column as usize;
                while visited[node] != column {
                    unsafe { (*output_ptr).lower.row_indices[cursors[node]] = column as u32 };
                    cursors[node] += 1;
                    visited[node] = column;
                    node = parent[node];
                }
            }
        }

        StaticCscPattern::<N, N, MAX_L_NNZ>::validate_parts(
            unsafe { &(&(*output_ptr).lower.row_indices)[..total_nnz] },
            &column_starts,
            total_nnz,
        )?;
        unsafe {
            for column in 0..N {
                (*output_ptr).lower.column_starts[column] = column_starts[column] as u32;
            }
            (*output_ptr).lower.nnz = total_nnz;
            Self::from_lower_with_ordering_into(
                &(*output_ptr).lower,
                StaticCscOrdering::identity(),
                output,
            );
        }
        // SAFETY: `from_lower_with_ordering_into` initialized the output above.
        unsafe { (*output.as_mut_ptr()).with_input_pattern_mut(matrix) };
        Ok(())
    }

    // The usual factor capacity is at least the input capacity, so the main path can reuse the
    // destination arrays. Retain a generic fallback for callers that choose a smaller factor
    // capacity; this path is rejected later if the actual fill does not fit.
    #[inline(never)]
    fn analyze_natural_with_local_scratch<const MAX_A_NNZ: usize, T: Real + Copy + Zero>(
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        output: &mut MaybeUninit<Self>,
    ) -> Result<(), SparseCholeskyError> {
        let mut row_counts = [0usize; N];
        for column in 0..N {
            let start = matrix.column_starts()[column] as usize;
            let end = matrix.column_end(column).unwrap_or(matrix.nnz());
            for index in start..end {
                let row = matrix.row_indices()[index] as usize;
                if row > column {
                    row_counts[row] += 1;
                }
            }
        }
        let mut row_starts = [0usize; N];
        for row in 1..N {
            row_starts[row] = row_starts[row - 1] + row_counts[row - 1];
        }
        let mut row_cursor = row_starts;
        let mut upper_columns = [0usize; MAX_A_NNZ];
        for column in 0..N {
            let start = matrix.column_starts()[column] as usize;
            let end = matrix.column_end(column).unwrap_or(matrix.nnz());
            for index in start..end {
                let row = matrix.row_indices()[index] as usize;
                if row > column {
                    upper_columns[row_cursor[row]] = column;
                    row_cursor[row] += 1;
                }
            }
        }
        let mut visited = [usize::MAX; N];
        let mut parent = [usize::MAX; N];
        let mut column_counts = [1usize; N];
        for column in 0..N {
            visited[column] = column;
            let start = row_starts[column];
            let end = if column + 1 < N {
                row_starts[column + 1]
            } else {
                row_starts[column] + row_counts[column]
            };
            for &upper_column in &upper_columns[start..end] {
                let mut node = upper_column;
                while visited[node] != column {
                    if parent[node] == usize::MAX {
                        parent[node] = column;
                    }
                    column_counts[node] += 1;
                    visited[node] = column;
                    node = parent[node];
                }
            }
        }
        let mut column_starts = [0usize; N];
        for column in 1..N {
            column_starts[column] = column_starts[column - 1] + column_counts[column - 1];
        }
        let total_nnz = if N == 0 {
            0
        } else {
            column_starts[N - 1] + column_counts[N - 1]
        };
        if total_nnz > MAX_L_NNZ {
            return Err(SparseCholeskyError::CapacityExceeded);
        }
        let mut row_indices = [0u32; MAX_L_NNZ];
        for column in 0..N {
            row_indices[column_starts[column]] = column as u32;
        }
        let mut cursors = column_starts;
        for cursor in &mut cursors {
            *cursor += 1;
        }
        visited = [usize::MAX; N];
        for column in 0..N {
            visited[column] = column;
            let start = row_starts[column];
            let end = if column + 1 < N {
                row_starts[column + 1]
            } else {
                row_starts[column] + row_counts[column]
            };
            for &upper_column in &upper_columns[start..end] {
                let mut node = upper_column;
                while visited[node] != column {
                    row_indices[cursors[node]] = column as u32;
                    cursors[node] += 1;
                    visited[node] = column;
                    node = parent[node];
                }
            }
        }
        let lower =
            StaticCscPattern::from_parts(&row_indices[..total_nnz], &column_starts, total_nnz)?;
        Self::from_lower_with_ordering_into(&lower, StaticCscOrdering::identity(), output);
        unsafe { (*output.as_mut_ptr()).with_input_pattern_mut(matrix) };
        Ok(())
    }

    /// Analyzes the matrix using the deterministic fixed-workspace
    /// minimum-degree ordering.
    #[inline]
    pub fn analyze_with_minimum_degree<const MAX_A_NNZ: usize, T: Real + Copy + Zero>(
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<Self, SparseCholeskyError> {
        Self::analyze_with_ordering(matrix, StaticCscOrdering::minimum_degree(matrix))
    }

    /// Analyzes the matrix after applying a symmetric fixed-size ordering.
    #[inline]
    pub fn analyze_with_ordering<const MAX_A_NNZ: usize, T: Real + Copy + Zero>(
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        ordering: StaticCscOrdering<N>,
    ) -> Result<Self, SparseCholeskyError> {
        let mut output = MaybeUninit::uninit();
        Self::analyze_with_ordering_into(matrix, ordering, &mut output)?;
        // SAFETY: `analyze_with_ordering_into` initializes every field before returning `Ok`.
        Ok(unsafe { output.assume_init() })
    }

    /// Analyzes a matrix directly into caller-owned uninitialized storage.
    ///
    /// The caller may call `assume_init` on `output` only after this method returns `Ok`. Writing
    /// directly into the destination avoids returning the large fixed-capacity symbolic pattern
    /// by value.
    pub fn analyze_with_ordering_into<const MAX_A_NNZ: usize, T: Real + Copy + Zero>(
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        ordering: StaticCscOrdering<N>,
        output: &mut MaybeUninit<Self>,
    ) -> Result<(), SparseCholeskyError> {
        validate_symmetric_structure(matrix)?;
        if ordering.is_identity() {
            return Self::analyze_natural_into(matrix, output);
        }
        let permuted = ordering.permute(matrix)?;
        Self::analyze_natural_into(&permuted, output)?;
        // The natural analysis is in permuted coordinates. Its metadata is reusable; subsequent
        // ordered numeric operations only need the ordering tag changed.
        // SAFETY: `analyze_natural_into` initialized the output above.
        unsafe { (*output.as_mut_ptr()).ordering = ordering };
        Ok(())
    }

    /// Analyzes a matrix that is already in the coordinates of `ordering`.
    ///
    /// This is useful when the caller has already applied a reusable sparse permutation. It
    /// performs the natural symbolic analysis in those coordinates without constructing another
    /// fixed-capacity permuted matrix.
    pub fn analyze_ordered_with_ordering_into<const MAX_A_NNZ: usize, T: Real + Copy + Zero>(
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        ordering: StaticCscOrdering<N>,
        output: &mut MaybeUninit<Self>,
    ) -> Result<(), SparseCholeskyError> {
        Self::analyze_natural_into(matrix, output)?;
        // SAFETY: natural analysis initialized the output before its ordering tag is updated.
        unsafe { (*output.as_mut_ptr()).ordering = ordering };
        Ok(())
    }

    /// Analyzes a matrix using fixed-workspace diagonal pivot selection.
    ///
    /// The returned pattern captures the numeric permutation selected from
    /// this matrix. A nonzero absolute pivot must exceed `threshold`.
    #[inline]
    pub fn analyze_with_diagonal_pivoting<const MAX_A_NNZ: usize, T: Real + Copy + Zero>(
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        threshold: T,
    ) -> Result<Self, SparseCholeskyError> {
        validate_symmetric_structure(matrix)?;
        let ordering = diagonal_pivot_ordering(matrix, threshold)?;
        Self::analyze_with_ordering(matrix, ordering)
    }

    /// Returns the analyzed lower-factor pattern.
    #[inline]
    pub fn lower(&self) -> &StaticCscPattern<N, N, MAX_L_NNZ> {
        &self.lower
    }

    /// Returns the ordering used by this symbolic factorization.
    #[inline]
    pub const fn ordering(&self) -> StaticCscOrdering<N> {
        self.ordering
    }

    /// Validates and transforms a symmetric matrix into reusable ordered
    /// lower-triangular coordinates.
    #[inline]
    pub fn prepare_ordered<const MAX_A_NNZ: usize, T: Real + Copy + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<StaticCscMatrix<N, N, MAX_A_NNZ, T>, SparseCholeskyError> {
        validate_symmetric_structure(matrix)?;
        let ordered = self.ordering.permute(matrix)?;
        self.validate_factor_pattern(&ordered)?;
        Ok(ordered)
    }

    /// Prepares ordered coordinates using a caller-retained permutation map.
    ///
    /// Build the map once with [`StaticCscOrdering::permutation_for_pattern`]
    /// when the same sparse structure is transformed repeatedly.
    #[inline]
    pub fn prepare_ordered_with_permutation<const MAX_A_NNZ: usize, T: Real + Copy + Zero>(
        &self,
        permutation: &StaticCscPermutation<N, MAX_A_NNZ>,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<StaticCscMatrix<N, N, MAX_A_NNZ, T>, SparseCholeskyError> {
        validate_symmetric_structure(matrix)?;
        let ordered = permutation.apply(matrix);
        self.validate_factor_pattern(&ordered)?;
        Ok(ordered)
    }

    /// Computes numeric values using this symbolic pattern.
    ///
    /// The input is interpreted using its lower triangle, as in Eigen's
    /// `UpLo=Lower` sparse LLT mode. A matching upper-triangle entry may also
    /// be present; it is validated and ignored for the numeric update.
    #[inline]
    pub fn factor<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<StaticCscCholesky<N, MAX_L_NNZ, T>, SparseCholeskyError> {
        let mut factor = StaticCscCholesky {
            lower: StaticCscMatrix {
                values: [T::zero(); MAX_L_NNZ],
                pattern: self.lower,
            },
            ordering: StaticCscOrdering::identity(),
        };
        self.factorize(matrix, &mut factor)?;
        Ok(factor)
    }

    /// Computes numeric values into reusable factor storage.
    #[inline]
    fn factorize<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        output: &mut StaticCscCholesky<N, MAX_L_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        validate_symmetric_structure(matrix)?;
        if !self.ordering.is_identity() {
            let permuted = self.ordering.permute(matrix)?;
            self.factor_natural_into(&permuted, true, false, output)?;
            output.ordering = self.ordering;
            return Ok(());
        }
        self.factor_natural_into(matrix, true, false, output)
    }

    /// Refactors an analyzed matrix into reusable storage without repeating
    /// symmetry or pattern validation. The matrix must retain its analyzed
    /// sparsity pattern; use [`Self::factor`] when that cannot be
    /// guaranteed.
    #[inline]
    fn refactorize<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        output: &mut StaticCscCholesky<N, MAX_L_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        if !self.ordering.is_identity() {
            let permuted = self.ordering.permute(matrix)?;
            self.factor_natural_into(&permuted, false, true, output)?;
            output.ordering = self.ordering;
            return Ok(());
        }
        self.factor_natural_into(matrix, false, true, output)
    }

    /// Factors a matrix that has already been transformed into this pattern's
    /// ordered coordinates. This avoids repeating the symmetric permutation
    /// and structural validation when numeric values are updated under a
    /// reused symbolic pattern. The matrix must retain the analyzed ordered
    /// sparsity pattern; use [`Self::factor`] when that cannot be guaranteed.
    #[inline]
    pub fn factor_ordered<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<StaticCscCholesky<N, MAX_L_NNZ, T>, SparseCholeskyError> {
        let mut factor = StaticCscCholesky {
            lower: StaticCscMatrix {
                values: [T::zero(); MAX_L_NNZ],
                pattern: self.lower,
            },
            ordering: self.ordering,
        };
        self.factorize_ordered(matrix, &mut factor)?;
        Ok(factor)
    }

    /// Factors ordered coordinates into reusable factor storage.
    #[inline]
    fn factorize_ordered<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        output: &mut StaticCscCholesky<N, MAX_L_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        self.factor_natural_into(matrix, false, false, output)?;
        output.ordering = self.ordering;
        Ok(())
    }

    /// Computes a fixed-capacity sparse LDLᵀ factorization using this pattern.
    #[inline]
    pub fn factor_ldlt<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<StaticCscLdlt<N, MAX_L_NNZ, T>, SparseCholeskyError> {
        let mut factor = StaticCscLdlt {
            lower: StaticCscMatrix {
                values: [T::zero(); MAX_L_NNZ],
                pattern: self.lower,
            },
            diagonal: [T::zero(); N],
            ordering: StaticCscOrdering::identity(),
        };
        self.factorize_ldlt(matrix, &mut factor)?;
        Ok(factor)
    }

    /// Computes sparse LDLᵀ values into reusable factor storage.
    #[inline]
    fn factorize_ldlt<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        output: &mut StaticCscLdlt<N, MAX_L_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        validate_symmetric_structure(matrix)?;
        if !self.ordering.is_identity() {
            let permuted = self.ordering.permute(matrix)?;
            self.factor_ldlt_natural_into(&permuted, true, false, output)?;
            output.ordering = self.ordering;
            return Ok(());
        }
        self.factor_ldlt_natural_into(matrix, true, false, output)
    }

    /// Refactors sparse LDLᵀ values without repeating symmetry or pattern
    /// validation. The matrix must retain its analyzed sparsity pattern.
    #[inline]
    pub(crate) fn refactorize_ldlt<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        output: &mut StaticCscLdlt<N, MAX_L_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        if !self.ordering.is_identity() {
            let permuted = self.ordering.permute(matrix)?;
            self.factor_ldlt_natural_into(&permuted, false, true, output)?;
            output.ordering = self.ordering;
            return Ok(());
        }
        self.factor_ldlt_natural_into(matrix, false, true, output)
    }

    /// Factors already ordered lower-triangular coordinates with LDLᵀ.
    #[inline]
    pub fn factor_ldlt_ordered<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<StaticCscLdlt<N, MAX_L_NNZ, T>, SparseCholeskyError> {
        let mut factor = MaybeUninit::uninit();
        self.factor_ldlt_ordered_into(matrix, &mut factor)?;
        // SAFETY: `factor_ldlt_ordered_into` initializes every field before returning `Ok`.
        Ok(unsafe { factor.assume_init() })
    }

    /// Computes ordered LDLᵀ values directly into caller-owned uninitialized storage.
    ///
    /// The caller may call `assume_init` on `output` only after this method returns `Ok`. This
    /// avoids returning the large fixed-capacity numeric factor by value.
    pub fn factor_ldlt_ordered_into<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        output: &mut MaybeUninit<StaticCscLdlt<N, MAX_L_NNZ, T>>,
    ) -> Result<(), SparseCholeskyError> {
        let output = output.as_mut_ptr();
        // SAFETY: every field is initialized exactly once before factorization writes numeric
        // values into the output.
        unsafe {
            let values = ptr::addr_of_mut!((*output).lower.values).cast::<T>();
            for index in 0..MAX_L_NNZ {
                values.add(index).write(T::zero());
            }
            ptr::addr_of_mut!((*output).lower.pattern).write(self.lower);
            let diagonal = ptr::addr_of_mut!((*output).diagonal).cast::<T>();
            for index in 0..N {
                diagonal.add(index).write(T::zero());
            }
            ptr::addr_of_mut!((*output).ordering).write(self.ordering);
        }
        // SAFETY: the factor storage was initialized immediately above.
        unsafe { self.factorize_ldlt_ordered(matrix, &mut *output) }
    }

    /// Factors ordered coordinates into reusable LDLᵀ storage.
    #[inline]
    pub(crate) fn factorize_ldlt_ordered<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        output: &mut StaticCscLdlt<N, MAX_L_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        self.factor_ldlt_natural_into(matrix, false, false, output)?;
        output.ordering = self.ordering;
        Ok(())
    }

    fn factor_ldlt_natural_into<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        validate_pattern: bool,
        copy_pattern: bool,
        output: &mut StaticCscLdlt<N, MAX_L_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        if N != 0 && self.input_diagonal_indices[0] != u32::MAX {
            return self.factor_ldlt_natural_into_aggregate(
                matrix,
                validate_pattern,
                copy_pattern,
                output,
            );
        }
        self.factor_ldlt_natural_into_left_looking(matrix, validate_pattern, copy_pattern, output)
    }

    fn factor_ldlt_natural_into_aggregate<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        validate_pattern: bool,
        copy_pattern: bool,
        output: &mut StaticCscLdlt<N, MAX_L_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        if validate_pattern {
            self.validate_factor_pattern(matrix)?;
        }
        if copy_pattern {
            output.lower.pattern = self.lower;
        }
        output.ordering = StaticCscOrdering::identity();

        let mut nonzeros_per_column = [0usize; N];
        let mut aggregate = [T::zero(); N];
        let matrix_values = matrix.values().as_ptr();
        let aggregate_update_starts = self.aggregate_update_starts.as_ptr();
        let aggregate_update_indices = self.aggregate_update_indices.as_ptr();
        let factor_column_starts = self.lower.column_starts().as_ptr();
        let factor_rows = self.lower.row_indices().as_ptr();
        let factor_row_starts = self.factor_row_starts.as_ptr();
        let factor_contiguous = self.factor_contiguous.as_ptr();
        let factor_values = output.lower.values_mut().as_mut_ptr();
        let diagonal_values = output.diagonal.as_mut_ptr();
        let aggregate_ptr = aggregate.as_mut_ptr();
        let nonzeros_ptr = nonzeros_per_column.as_mut_ptr();
        let numeric_pattern_starts = self.numeric_pattern_starts.as_ptr();
        let numeric_pattern_columns = self.numeric_pattern_columns.as_ptr();
        let aggregate_update_columns = self.aggregate_update_columns.as_ptr();

        // SAFETY: symbolic analysis validates every fixed-capacity schedule,
        // row index, and source index used below before numeric factorization.
        unsafe {
            for column in 0..N {
                let diagonal_index = *factor_column_starts.add(column) as usize;
                let diagonal_source = self.input_diagonal_indices[column];
                if diagonal_source != u32::MAX {
                    *aggregate_ptr.add(column) =
                        *aggregate_ptr.add(column) + *matrix_values.add(diagonal_source as usize);
                }

                let update_start = *aggregate_update_starts.add(column) as usize;
                let update_end = if column + 1 < N {
                    *aggregate_update_starts.add(column + 1) as usize
                } else {
                    self.aggregate_update_nnz
                };
                for update in update_start..update_end {
                    let source_index = *aggregate_update_indices.add(update) as usize;
                    let node = *aggregate_update_columns.add(update) as usize;
                    *aggregate_ptr.add(node) =
                        *aggregate_ptr.add(node) + *matrix_values.add(source_index);
                }

                let mut diagonal = *aggregate_ptr.add(column);
                *aggregate_ptr.add(column) = T::zero();
                let pattern_start = *numeric_pattern_starts.add(column) as usize;
                let pattern_end = if column + 1 < N {
                    *numeric_pattern_starts.add(column + 1) as usize
                } else {
                    self.numeric_pattern_nnz
                };
                let mut pattern_index = pattern_start;
                while pattern_index < pattern_end {
                    let previous = *numeric_pattern_columns.add(pattern_index) as usize;
                    let aggregate_previous = *aggregate_ptr.add(previous);
                    let lower_value = aggregate_previous / *diagonal_values.add(previous);
                    let start = *factor_column_starts.add(previous) as usize;
                    let end = start + 1 + *nonzeros_ptr.add(previous);
                    *aggregate_ptr.add(previous) = T::zero();
                    let mut index = start + 1;
                    if *factor_contiguous.add(previous) {
                        let row = *factor_row_starts.add(previous) as usize;
                        let count = end - index;
                        // SAFETY: symbolic analysis proves that the
                        // contiguous factor rows occupy `row..row + count`
                        // within `aggregate`, and that `index..end` is within
                        // the factor values. These slices are disjoint
                        // allocations, so LLVM can optimize the update loop
                        // without changing its element order.
                        let aggregate_values =
                            core::slice::from_raw_parts_mut(aggregate_ptr.add(row), count);
                        let factor_column =
                            core::slice::from_raw_parts(factor_values.add(index), count);
                        for (aggregate_value, factor_value) in
                            aggregate_values.iter_mut().zip(factor_column)
                        {
                            *aggregate_value =
                                *aggregate_value - *factor_value * aggregate_previous;
                        }
                    } else {
                        while index < end {
                            let row = *factor_rows.add(index) as usize;
                            *aggregate_ptr.add(row) = *aggregate_ptr.add(row)
                                - *factor_values.add(index) * aggregate_previous;
                            index += 1;
                        }
                    }
                    *factor_values.add(end) = lower_value;
                    diagonal = diagonal - lower_value * aggregate_previous;
                    *nonzeros_ptr.add(previous) += 1;
                    pattern_index += 1;
                }

                if !diagonal.is_finite() {
                    return Err(SparseCholeskyError::NonFinite);
                }
                if diagonal == T::zero() {
                    return Err(SparseCholeskyError::ZeroPivot);
                }
                *factor_values.add(diagonal_index) = T::one();
                *diagonal_values.add(column) = diagonal;
            }
        }
        Ok(())
    }

    fn factor_ldlt_natural_into_left_looking<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        validate_pattern: bool,
        copy_pattern: bool,
        output: &mut StaticCscLdlt<N, MAX_L_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        if validate_pattern {
            self.validate_factor_pattern(matrix)?;
        }
        if copy_pattern {
            output.lower.pattern = self.lower;
        }
        output.ordering = StaticCscOrdering::identity();

        let mut work = [T::zero(); N];
        for column in 0..N {
            for value in &mut work[column..] {
                *value = T::zero();
            }
            let matrix_start = matrix.column_starts()[column] as usize;
            let matrix_end = matrix.column_end(column).unwrap_or(matrix.nnz());
            for index in matrix_start..matrix_end {
                let row = matrix.row_indices()[index] as usize;
                if row >= column {
                    work[row] = matrix.values()[index];
                }
            }

            let update_start = self.update_starts[column];
            let update_end = if column + 1 < N {
                self.update_starts[column + 1]
            } else {
                self.update_nnz
            };
            for update in update_start..update_end {
                let lower_index = self.update_indices[update] as usize;
                let previous = self.update_columns[update] as usize;
                let scale = output.lower.values()[lower_index] * output.diagonal[previous];
                let end = output
                    .lower
                    .column_end(previous)
                    .unwrap_or(output.lower.nnz());
                if self.update_contiguous[update] {
                    let row_start = self.update_row_starts[update] as usize;
                    for offset in 0..(end - lower_index) {
                        let row = row_start + offset;
                        work[row] = work[row] - output.lower.values()[lower_index + offset] * scale;
                    }
                } else {
                    for index in lower_index..end {
                        let row = output.lower.row_indices()[index] as usize;
                        work[row] = work[row] - output.lower.values()[index] * scale;
                    }
                }
            }

            let diagonal = work[column];
            if !diagonal.is_finite() {
                return Err(SparseCholeskyError::NonFinite);
            }
            if diagonal == T::zero() {
                return Err(SparseCholeskyError::ZeroPivot);
            }
            output.diagonal[column] = diagonal;
            let start = output.lower.column_starts()[column] as usize;
            let end = output
                .lower
                .column_end(column)
                .unwrap_or(output.lower.nnz());
            output.lower.values_mut()[start] = T::one();
            for index in (start + 1)..end {
                let row = output.lower.row_indices()[index] as usize;
                let value = work[row] / diagonal;
                if !value.is_finite() {
                    return Err(SparseCholeskyError::NonFinite);
                }
                output.lower.values_mut()[index] = value;
            }
        }

        Ok(())
    }

    fn factor_natural_into<const MAX_A_NNZ: usize, T: Real + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
        validate_pattern: bool,
        copy_pattern: bool,
        output: &mut StaticCscCholesky<N, MAX_L_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        if validate_pattern {
            self.validate_factor_pattern(matrix)?;
        }
        if copy_pattern {
            output.lower.pattern = self.lower;
        }
        output.ordering = StaticCscOrdering::identity();

        let mut work = [T::zero(); N];
        for column in 0..N {
            for value in &mut work[column..] {
                *value = T::zero();
            }
            let matrix_start = matrix.column_starts()[column] as usize;
            let matrix_end = matrix.column_end(column).unwrap_or(matrix.nnz());
            for index in matrix_start..matrix_end {
                let row = matrix.row_indices()[index] as usize;
                if row >= column {
                    work[row] = matrix.values()[index];
                }
            }

            let update_start = self.update_starts[column];
            let update_end = if column + 1 < N {
                self.update_starts[column + 1]
            } else {
                self.update_nnz
            };
            for update in update_start..update_end {
                let lower_index = self.update_indices[update] as usize;
                let previous = self.update_columns[update] as usize;
                let lower_column = output.lower.values()[lower_index];
                let end = output
                    .lower
                    .column_end(previous)
                    .unwrap_or(output.lower.nnz());
                if self.update_contiguous[update] {
                    let row_start = self.update_row_starts[update] as usize;
                    for offset in 0..(end - lower_index) {
                        let row = row_start + offset;
                        work[row] =
                            work[row] - output.lower.values()[lower_index + offset] * lower_column;
                    }
                } else {
                    for index in lower_index..end {
                        let row = output.lower.row_indices()[index] as usize;
                        work[row] = work[row] - output.lower.values()[index] * lower_column;
                    }
                }
            }

            let diagonal = work[column];
            if !diagonal.is_finite() {
                return Err(SparseCholeskyError::NonFinite);
            }
            if diagonal <= T::zero() {
                return Err(SparseCholeskyError::NotPositiveDefinite);
            }
            let root = diagonal.sqrt();
            if !root.is_finite() || root <= T::zero() {
                return Err(SparseCholeskyError::NonFinite);
            }
            let start = output.lower.column_starts()[column] as usize;
            let end = output
                .lower
                .column_end(column)
                .unwrap_or(output.lower.nnz());
            output.lower.values_mut()[start] = root;
            for index in (start + 1)..end {
                let row = output.lower.row_indices()[index] as usize;
                let value = work[row] / root;
                if !value.is_finite() {
                    return Err(SparseCholeskyError::NonFinite);
                }
                output.lower.values_mut()[index] = value;
            }
        }

        Ok(())
    }

    fn validate_factor_pattern<const MAX_A_NNZ: usize, T: Copy + Zero>(
        &self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        for column in 0..N {
            let start = matrix.column_starts()[column] as usize;
            let end = matrix.column_end(column).unwrap_or(matrix.nnz());
            for index in start..end {
                let row = matrix.row_indices()[index] as usize;
                let (lower_row, lower_column) = if row >= column {
                    (row, column)
                } else {
                    (column, row)
                };
                let lower_start = self.lower.column_starts()[lower_column] as usize;
                let lower_end = self
                    .lower
                    .column_end(lower_column)
                    .unwrap_or(self.lower.nnz());
                if !self.lower.row_indices()[lower_start..lower_end].contains(&(lower_row as u32)) {
                    return Err(SparseCholeskyError::PatternMismatch);
                }
            }
        }
        Ok(())
    }
}

fn validate_symmetric_structure<const N: usize, const MAX_NNZ: usize, T: Real + Copy>(
    matrix: &StaticCscMatrix<N, N, MAX_NNZ, T>,
) -> Result<(), SparseCholeskyError> {
    for column in 0..N {
        let start = matrix.column_starts()[column] as usize;
        let end = matrix.column_end(column).unwrap_or(matrix.nnz());
        for index in start..end {
            let row = matrix.row_indices()[index] as usize;
            let value = matrix.values()[index];
            if !value.is_finite() {
                return Err(SparseCholeskyError::NonFinite);
            }
            if row < column {
                let transpose = matrix
                    .get(column, row)
                    .copied()
                    .ok_or(SparseCholeskyError::NonSymmetric)?;
                if !transpose.is_finite() {
                    return Err(SparseCholeskyError::NonFinite);
                }
                let scale = T::one().max(value.abs()).max(transpose.abs());
                let tolerance = T::epsilon() * T::from(100).unwrap_or(T::one()) * scale;
                if (value - transpose).abs() > tolerance {
                    return Err(SparseCholeskyError::NonSymmetric);
                }
            }
        }
    }
    Ok(())
}

#[allow(clippy::needless_range_loop)]
fn diagonal_pivot_ordering<const N: usize, const MAX_NNZ: usize, T: Real + Copy + Zero>(
    matrix: &StaticCscMatrix<N, N, MAX_NNZ, T>,
    threshold: T,
) -> Result<StaticCscOrdering<N>, SparseCholeskyError> {
    if !threshold.is_finite() {
        return Err(SparseCholeskyError::NonFinite);
    }
    let threshold = threshold.abs();
    let mut work = [[T::zero(); N]; N];
    for column in 0..N {
        let start = matrix.column_starts()[column] as usize;
        let end = matrix.column_end(column).unwrap_or(matrix.nnz());
        for index in start..end {
            let row = matrix.row_indices()[index] as usize;
            if row >= column {
                let value = matrix.values()[index];
                work[row][column] = value;
                work[column][row] = value;
            }
        }
    }

    let mut permutation = [0; N];
    for (index, value) in permutation.iter_mut().enumerate() {
        *value = index;
    }
    for pivot_position in 0..N {
        let mut pivot = pivot_position;
        let mut magnitude = work[pivot_position][pivot_position].abs();
        for candidate in (pivot_position + 1)..N {
            let candidate_magnitude = work[candidate][candidate].abs();
            if candidate_magnitude > magnitude {
                magnitude = candidate_magnitude;
                pivot = candidate;
            }
        }
        if !magnitude.is_finite() {
            return Err(SparseCholeskyError::NonFinite);
        }
        if magnitude <= threshold {
            return Err(SparseCholeskyError::ZeroPivot);
        }
        if pivot != pivot_position {
            work.swap(pivot_position, pivot);
            for index in 0..N {
                work[index].swap(pivot_position, pivot);
            }
            permutation.swap(pivot_position, pivot);
        }

        let diagonal = work[pivot_position][pivot_position];
        for row in (pivot_position + 1)..N {
            work[row][pivot_position] = work[row][pivot_position] / diagonal;
            work[pivot_position][row] = work[row][pivot_position];
            if !work[row][pivot_position].is_finite() {
                return Err(SparseCholeskyError::NonFinite);
            }
        }
        for column in (pivot_position + 1)..N {
            let lower_column = work[column][pivot_position];
            for row in column..N {
                work[row][column] =
                    work[row][column] - work[row][pivot_position] * diagonal * lower_column;
                work[column][row] = work[row][column];
                if !work[row][column].is_finite() {
                    return Err(SparseCholeskyError::NonFinite);
                }
            }
        }
    }
    StaticCscOrdering::from_permutation(&permutation).map_err(SparseCholeskyError::from)
}

/// Numeric fixed-capacity simplicial sparse Cholesky factorization.
///
/// The factor stores a lower-triangular `L` in CSC form such that
/// `A = L * Lᵀ`. Any symbolic fill must fit in `MAX_L_NNZ` entries.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct StaticCscCholesky<const N: usize, const MAX_L_NNZ: usize, T = f32> {
    lower: StaticCscMatrix<N, N, MAX_L_NNZ, T>,
    ordering: StaticCscOrdering<N>,
}

impl<const N: usize, const MAX_L_NNZ: usize, T: Real> StaticCscCholesky<N, MAX_L_NNZ, T> {
    /// Returns the exact inline storage footprint of this numeric factor.
    #[inline]
    pub const fn storage_bytes() -> usize {
        core::mem::size_of::<Self>()
    }

    /// Performs symbolic analysis and numeric factorization in one step.
    ///
    /// This convenience method is appropriate when the structure is used only
    /// once. For repeated solves, retain a [`StaticCscCholeskyPattern`] and
    /// call [`StaticCscCholeskyPattern::factor`] followed by
    /// [`StaticCscCholesky::recompute`].
    #[inline]
    pub fn decompose<const MAX_A_NNZ: usize>(
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<Self, SparseCholeskyError> {
        StaticCscCholeskyPattern::analyze(matrix)?.factor(matrix)
    }

    /// Performs minimum-degree symbolic analysis and numeric factorization.
    #[inline]
    pub fn decompose_with_minimum_degree<const MAX_A_NNZ: usize>(
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<Self, SparseCholeskyError> {
        StaticCscCholeskyPattern::analyze_with_minimum_degree(matrix)?.factor(matrix)
    }

    /// Returns the reusable symbolic factor pattern.
    #[inline]
    pub fn pattern(&self) -> StaticCscCholeskyPattern<N, MAX_L_NNZ> {
        StaticCscCholeskyPattern::from_lower_with_ordering(*self.lower.pattern(), self.ordering)
    }

    /// Recomputes numeric values using this factor's analyzed sparsity pattern.
    #[inline]
    pub fn recompute<const MAX_A_NNZ: usize>(
        &mut self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        let pattern = self.pattern();
        pattern.refactorize(matrix, self)
    }

    /// Recomputes numeric values using caller-retained symbolic metadata.
    ///
    /// This avoids rebuilding the update schedule on every iteration. Retain
    /// the [`StaticCscCholeskyPattern`] returned by symbolic analysis when a
    /// factor is updated repeatedly.
    #[inline]
    pub fn recompute_with_pattern<const MAX_A_NNZ: usize>(
        &mut self,
        pattern: &StaticCscCholeskyPattern<N, MAX_L_NNZ>,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        pattern.refactorize(matrix, self)
    }

    /// Recomputes numeric values from coordinates already transformed by
    /// [`StaticCscCholeskyPattern::prepare_ordered`].
    #[inline]
    pub fn recompute_ordered<const MAX_A_NNZ: usize>(
        &mut self,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        let pattern = self.pattern();
        pattern.factorize_ordered(matrix, self)
    }

    /// Recomputes ordered coordinates using caller-retained symbolic metadata.
    #[inline]
    pub fn recompute_ordered_with_pattern<const MAX_A_NNZ: usize>(
        &mut self,
        pattern: &StaticCscCholeskyPattern<N, MAX_L_NNZ>,
        matrix: &StaticCscMatrix<N, N, MAX_A_NNZ, T>,
    ) -> Result<(), SparseCholeskyError> {
        pattern.factorize_ordered(matrix, self)
    }

    /// Returns the sparse lower-triangular factor.
    #[inline]
    pub fn lower(&self) -> &StaticCscMatrix<N, N, MAX_L_NNZ, T> {
        &self.lower
    }

    /// Solves `A * X = B` using the sparse factor.
    ///
    /// The returned matrix is fixed-size and stored on the caller's stack (or
    /// wherever the factor's owning value is stored); no heap allocation is
    /// performed by the solve.
    #[inline]
    pub fn solve<const P: usize>(&self, rhs: &Matrix<N, P, T>) -> Matrix<N, P, T> {
        let mut output = *rhs;
        self.solve_in_place(&mut output);
        output
    }

    /// Solves `A * X = B` into caller-provided storage.
    #[inline]
    pub fn solve_into<const P: usize>(&self, rhs: &Matrix<N, P, T>, output: &mut Matrix<N, P, T>) {
        *output = *rhs;
        self.solve_in_place(output);
    }

    /// Solves `A * X = B` in place using forward and backward substitution.
    #[inline]
    pub fn solve_in_place<const P: usize>(&self, rhs: &mut Matrix<N, P, T>) {
        if !self.ordering.is_identity() {
            let mut permuted = Matrix::<N, P, T>::zeros();
            for ordered in 0..N {
                let original = self.ordering.permutation()[ordered];
                for column in 0..P {
                    permuted[(ordered, column)] = rhs[(original, column)];
                }
            }
            self.solve_natural_in_place(&mut permuted);
            for ordered in 0..N {
                let original = self.ordering.permutation()[ordered];
                for column in 0..P {
                    rhs[(original, column)] = permuted[(ordered, column)];
                }
            }
            return;
        }
        self.solve_natural_in_place(rhs);
    }

    fn solve_natural_in_place<const P: usize>(&self, rhs: &mut Matrix<N, P, T>) {
        let rhs_ptr = rhs.as_mut_slice().as_mut_ptr();
        let lower_rows = self.lower.row_indices().as_ptr();
        let lower_values = self.lower.values().as_ptr();

        // SAFETY: the sparse pattern is validated at construction, so every
        // stored row index is below N and every CSC range is within the
        // corresponding value array. Matrix storage is column-major with a
        // stride of N for each RHS column.
        unsafe {
            for row in 0..N {
                let start = self.lower.column_starts()[row] as usize;
                let end = self.lower.column_end(row).unwrap_or(self.lower.nnz());
                let diagonal = *lower_values.add(start);
                for column in 0..P {
                    let entry = rhs_ptr.add(row + column * N);
                    *entry = *entry / diagonal;
                }
                for index in (start + 1)..end {
                    let target = *lower_rows.add(index) as usize;
                    let value = *lower_values.add(index);
                    for column in 0..P {
                        let target_ptr = rhs_ptr.add(target + column * N);
                        let row_ptr = rhs_ptr.add(row + column * N);
                        *target_ptr = *target_ptr - value * *row_ptr;
                    }
                }
            }

            for row in (0..N).rev() {
                let start = self.lower.column_starts()[row] as usize;
                let end = self.lower.column_end(row).unwrap_or(self.lower.nnz());
                let diagonal = *lower_values.add(start);
                for index in (start + 1)..end {
                    let source = *lower_rows.add(index) as usize;
                    let value = *lower_values.add(index);
                    for column in 0..P {
                        let row_ptr = rhs_ptr.add(row + column * N);
                        let source_ptr = rhs_ptr.add(source + column * N);
                        *row_ptr = *row_ptr - value * *source_ptr;
                    }
                }
                for column in 0..P {
                    let entry = rhs_ptr.add(row + column * N);
                    *entry = *entry / diagonal;
                }
            }
        }
    }
}
