#!/usr/bin/env python3
"""Run the Rust tutorials and render their exports, without a Python solver.

Only the standard library is needed. Generated assets are deliberately not
committed: a failed execution must fail the documentation build, not publish
an old chart. Use --check to execute again and compare all generated bytes.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import html
import io
import json
import math
import os
from pathlib import Path
import platform
import shutil
import subprocess
import sys
import tempfile

LINE_COLUMNS = "x,observed_y,fitted_y,residual,slope,intercept,residual_norm,sample_count".split(",")
KALMAN_COLUMNS = (
    "time_s,measured_m,dt_s,acceleration_variance,measurement_variance,"
    "initial_position_m,initial_velocity_m_s,initial_p00,initial_p01,initial_p10,initial_p11,"
    "predicted_position_m,predicted_velocity_m_s,predicted_p00,predicted_p01,predicted_p10,predicted_p11,"
    "position_m,velocity_m_s,p00,p01,p10,p11,innovation_m,innovation_variance,position_gain,velocity_gain,sample_count"
).split(",")
EXAMPLES = {"mapped_least_squares": LINE_COLUMNS, "kalman_1d": KALMAN_COLUMNS}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def close(actual: float, expected: float, label: str, tolerance: float = 2e-5) -> None:
    require(math.isclose(actual, expected, rel_tol=tolerance, abs_tol=tolerance), label)


def read_csv(text: str, columns: list[str]) -> list[dict[str, float]]:
    reader = csv.DictReader(io.StringIO(text))
    require(reader.fieldnames == columns, "unexpected CSV schema (including column order)")
    rows = []
    for index, row in enumerate(reader, 1):
        require(None not in row and all(row.get(key) is not None for key in columns),
                f"malformed CSV row {index}")
        values = {key: float(row[key]) for key in columns}
        require(all(math.isfinite(value) for value in values.values()), f"non-finite row {index}")
        rows.append(values)
    require(bool(rows), "empty CSV export")
    require(all(row["sample_count"] == len(rows) for row in rows), "truncated or inconsistent sample count")
    return rows


def validate_line(rows: list[dict[str, float]]) -> None:
    for row in rows:
        for key in ("slope", "intercept", "residual_norm"):
            require(row[key] == rows[0][key], f"inconsistent line-fit {key}")
        close(row["residual"], row["observed_y"] - row["fitted_y"], "residual sign/value", 1e-10)
        close(row["fitted_y"], row["slope"] * row["x"] + row["intercept"], "fitted value", 1e-10)
    close(rows[0]["residual_norm"], math.sqrt(sum(r["residual"] ** 2 for r in rows)),
          "residual norm", 1e-10)


def validate_kalman(rows: list[dict[str, float]]) -> None:
    constants = [key for key in KALMAN_COLUMNS if key.startswith("initial_")]
    constants += ["dt_s", "acceleration_variance", "measurement_variance"]
    for index, row in enumerate(rows, 1):
        require(all(row[key] == rows[0][key] for key in constants), "changing initial conditions/settings")
        require(row["dt_s"] > 0 and row["measurement_variance"] > 0
                and row["acceleration_variance"] >= 0, "invalid uncertainty or time settings")
        close(row["time_s"], index * row["dt_s"], "sample time (first reading follows prediction)")
        close(row["innovation_m"], row["measured_m"] - row["predicted_position_m"], "innovation")
        close(row["innovation_variance"], row["predicted_p00"] + row["measurement_variance"], "innovation variance")
        require(row["innovation_variance"] > 0, "nonpositive innovation variance")
        close(row["position_gain"], row["predicted_p00"] / row["innovation_variance"], "position gain")
        close(row["velocity_gain"], row["predicted_p10"] / row["innovation_variance"], "velocity gain")
        for state, gain in (("position_m", "position_gain"), ("velocity_m_s", "velocity_gain")):
            close(row[state], row["predicted_" + state] + row[gain] * row["innovation_m"], "correction")
        for prefix in ("initial_", "predicted_", ""):
            a, b, c, d = (row[prefix + key] for key in ("p00", "p01", "p10", "p11"))
            require(a >= 0 and d >= 0, "negative covariance diagonal")
            close(b, c, "asymmetric covariance")
            require(a * d - b * c >= -2e-5 * max(1.0, abs(a * d)), "indefinite covariance")


def line_text(rows: list[dict[str, float]]) -> str:
    first = rows[0]
    lines = [f"slope = {first['slope']:.3f}, intercept = {first['intercept']:.3f}",
             "x observed_y fitted_y residual"]
    lines += [f"{r['x']:.1f} {r['observed_y']:.3f} {r['fitted_y']:.3f} {r['residual']:.3f}" for r in rows]
    lines.append(f"residual norm = {first['residual_norm']:.3f}")
    return "\n".join(lines) + "\n"


def kalman_text(rows: list[dict[str, float]]) -> str:
    return "time_s measured_m position_m velocity_m_s\n" + "".join(
        f"{r['time_s']:.0f} {r['measured_m']:.3f} {r['position_m']:.3f} {r['velocity_m_s']:.3f}\n"
        for r in rows
    )


class Svg:
    """Small, deterministic SVG vocabulary, not a plotting/solver framework."""
    def __init__(self, title: str, description: str):
        self.parts = [
            '<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="600" viewBox="0 0 1000 600" role="img" aria-labelledby="title desc">',
            f'<title id="title">{html.escape(title)}</title><desc id="desc">{html.escape(description)}</desc>',
            '<rect width="1000" height="600" rx="12" fill="white"/>',
            '<g font-family="system-ui, sans-serif" fill="currentColor">',
        ]
        self.text(40, 44, title, 25, weight="600")
        self.text(40, 74, description, 14)

    def text(self, x: float, y: float, text: str, size: int = 15, **attrs: str) -> None:
        extra = " ".join(f'{key}="{html.escape(str(value), quote=True)}"' for key, value in attrs.items())
        # Use explicit font-weight instead of a custom rendering dependency.
        extra = extra.replace('weight=', 'font-weight=')
        self.parts.append(f'<text x="{x:.3f}" y="{y:.3f}" font-size="{size}" {extra}>{html.escape(text)}</text>')

    def line(self, x1: float, y1: float, x2: float, y2: float, width: float = 1, opacity: float = 1) -> None:
        self.parts.append(f'<path d="M{x1:.3f},{y1:.3f} L{x2:.3f},{y2:.3f}" fill="none" stroke="currentColor" stroke-width="{width}" opacity="{opacity}"/>')

    def marker(self, x: float, y: float, cross: bool = False) -> None:
        if cross:
            self.line(x - 5, y - 5, x + 5, y + 5, 2)
            self.line(x - 5, y + 5, x + 5, y - 5, 2)
        else:
            self.parts.append(f'<circle cx="{x:.3f}" cy="{y:.3f}" r="4"/>')

    def finish(self) -> str:
        self.text(40, 573, "stack-algebra / executed Rust example", 13)
        return "\n".join(self.parts + ["</g></svg>\n"])


def limits(values: list[float], zero: bool = False) -> tuple[float, float, list[float]]:
    lo, hi = min(values), max(values)
    if zero:
        lo, hi = min(lo, 0), max(hi, 0)
    span = hi - lo or max(1.0, abs(lo) * 0.2)
    lo, hi = lo - span * 0.08, hi + span * 0.08
    raw = (hi - lo) / 5
    power = 10 ** math.floor(math.log10(raw))
    step = next(n for n in (1, 2, 5, 10) if n * power >= raw) * power
    ticks = [index * step for index in range(math.ceil(lo / step), math.floor(hi / step) + 1)]
    return lo, hi, ticks


def chart(title: str, description: str, rows: list[dict[str, float]], xkey: str,
          series: list[tuple[str, str, bool]], xlabel: str, ylabel: str,
          footer: str, residuals: bool = False, zero: bool = False) -> str:
    svg = Svg(title, description)
    xmin, xmax, xticks = limits([row[xkey] for row in rows])
    ymin, ymax, yticks = limits([row[key] for key, _, _ in series for row in rows], zero)
    px = lambda x: 100 + (x - xmin) / (xmax - xmin) * 840
    py = lambda y: 450 - (y - ymin) / (ymax - ymin) * 300
    for tick in xticks:
        x = px(tick)
        svg.line(x, 150, x, 450, opacity=0.12)
        svg.text(x, 476, f"{tick:g}", **{"text-anchor": "middle"})
    for tick in yticks:
        y = py(tick)
        svg.line(100, y, 940, y, opacity=0.12)
        svg.text(87, y + 5, f"{tick:g}", **{"text-anchor": "end"})
    svg.line(100, 150, 100, 450)
    svg.line(100, 450, 940, 450)
    svg.text(520, 508, xlabel, **{"text-anchor": "middle"})
    svg.text(100, 137, ylabel)
    for index, (key, label, cross) in enumerate(series):
        legend = 110 + index * 370
        svg.marker(legend, 107, cross)
        svg.text(legend + 15, 112, label)
        points = [(px(row[xkey]), py(row[key])) for row in rows]
        if not cross:
            # The line only joins the exported samples; no fitted/interpolated model is solved here.
            ordered = sorted(points)
            for a, b in zip(ordered, ordered[1:]):
                svg.line(*a, *b, width=2)
        for x, y in points:
            svg.marker(x, y, cross)
    if residuals:
        for row in rows:
            svg.line(px(row[xkey]), py(row["observed_y"]), px(row[xkey]), py(row["fitted_y"]), width=2, opacity=0.5)
    svg.text(40, 544, footer, 14)
    return svg.finish()


def first_update(row: dict[str, float]) -> str:
    svg = Svg("One reading updates position and velocity",
              f"First correction at t = {row['time_s']:g} s. All three rows describe this same instant.")
    groups = [
        ("Predict", row["predicted_position_m"], row["predicted_p00"], row["predicted_velocity_m_s"]),
        ("Measure", row["measured_m"], row["measurement_variance"], None),
        ("Correct", row["position_m"], row["p00"], row["velocity_m_s"]),
    ]
    bounds = [p + sign * math.sqrt(variance) for _, p, variance, _ in groups for sign in (-1, 1)]
    lo, hi, ticks = limits(bounds)
    px = lambda x: 170 + (x - lo) / (hi - lo) * 560
    svg.text(170, 112, "Position (m): shared scale; bands show ±1 standard deviation", 14)
    for tick in ticks:
        svg.text(px(tick), 143, f"{tick:g}", 13, **{"text-anchor": "middle"})
        svg.line(px(tick), 150, px(tick), 410, opacity=0.12)
    for index, (name, position, variance, velocity) in enumerate(groups):
        y = 195 + index * 98
        sigma = math.sqrt(variance)
        svg.text(40, y + 5, name, 20, weight="600")
        svg.line(170, y, 730, y, opacity=0.2)
        svg.line(px(position - sigma), y, px(position + sigma), y, width=18, opacity=0.16)
        svg.marker(px(position), y, name == "Measure")
        svg.text(170, y + 32, f"position {position:.3f} m   /   variance {variance:.3f} m²", 14)
        svg.text(765, y + 5, "Position only" if velocity is None else f"v = {velocity:.3f} m/s", 16)
    svg.text(40, 466, f"Innovation: {row['innovation_m']:.3f} m   |   Position gain: {row['position_gain']:.6f}   |   Velocity gain: {row['velocity_gain']:.6f} 1/s", 16)
    svg.text(40, 507, f"Initial state: p = {row['initial_position_m']:g} m, v = {row['initial_velocity_m_s']:g} m/s. No velocity measurement is supplied.", 14)
    svg.text(40, 536, "Bands express the model's marginal uncertainty, not measured error or a ground-truth trajectory.", 14)
    return svg.finish()


def render(line: list[dict[str, float]], kalman: list[dict[str, float]]) -> dict[str, str]:
    first = line[0]
    worst = max(line, key=lambda r: abs(r["residual"]))
    result = {
        "line-fit.svg": chart("Fit the model. Inspect what remains.",
            "A column-pivoted QR solve on the caller-owned design buffer.", line, "x",
            [("fitted_y", "Fitted values (joined)", False), ("observed_y", "Observations", True)], "Input x", "Observed / fitted y",
            f"y = {first['slope']:.3f}x {first['intercept']:+.3f}   |   Residual norm: {first['residual_norm']:.3f}", residuals=True),
        "line-fit-residuals.svg": chart("See the residuals on their own scale",
            "Observed minus fitted, using the residual vector exported by Rust.", line, "x",
            [("residual", "Residual", True)], "Input x", "Residual in y",
            f"Largest magnitude: {worst['residual']:+.3f} at x = {worst['x']:g}. This is a separate residual axis.", zero=True),
        "kalman-position.svg": chart("Estimate position from imperfect readings",
            "The actual input sequence and post-correction state from kalman_1d.rs.", kalman, "time_s",
            [("position_m", "Estimated position", False), ("measured_m", "Position reading", True)], "Time (s)", "Position (m)",
            "Lines join discrete estimates. No ground-truth trajectory is supplied.", zero=True),
        "kalman-velocity.svg": chart("Infer velocity from position readings",
            "Each value is exported after a predict-and-correct step; velocity is not measured.", kalman, "time_s",
            [("velocity_m_s", "Estimated velocity", False)], "Time (s)", "Velocity (m/s)",
            f"Initial estimate: {kalman[0]['initial_velocity_m_s']:g} m/s. Final estimate: {kalman[-1]['velocity_m_s']:.3f} m/s.", zero=True),
        "kalman-first-update.svg": first_update(kalman[0]),
    }
    return result


def capture(root: Path, command: list[str]) -> str:
    print("+ " + " ".join(command), flush=True)
    return subprocess.run(command, cwd=root, check=True, text=True,
                          stdout=subprocess.PIPE, timeout=1800).stdout


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def generate(root: Path, check: bool = False) -> None:
    output = root / "docs/generated/tutorials"
    if not check and output.exists():
        shutil.rmtree(output)
    build = root / "build"
    build.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="tutorial-assets-", dir=build) as temp:
        stage = Path(temp) / "assets"
        stage.mkdir()
        if not (root / "Cargo.lock").exists():
            capture(root, ["cargo", "generate-lockfile"])
        records = {}
        executions = []
        for name, columns in EXAMPLES.items():
            command = ["cargo", "run", "--locked", "--quiet", "--no-default-features", "--example", name]
            for extension, args in (("csv", ["--", "--csv"]), ("txt", [])):
                text = capture(root, command + args)
                (stage / f"{name}.{extension}").write_text(text, encoding="utf-8")
                executions.append({"command": command + args, "exit_code": 0, "stdout": f"{name}.{extension}"})
            records[name] = read_csv((stage / f"{name}.csv").read_text(), columns)
        line, kalman = records["mapped_least_squares"], records["kalman_1d"]
        validate_line(line)
        validate_kalman(kalman)
        # Check the actual human-mode stdout against the same reported numbers.
        # Formatting checks are not an independent numerical solver.
        for name, expected in (("mapped_least_squares", line_text(line)), ("kalman_1d", kalman_text(kalman))):
            require((stage / f"{name}.txt").read_text() == expected, f"{name}: text and CSV modes disagree")
        for filename, contents in render(line, kalman).items():
            (stage / filename).write_text(contents, encoding="utf-8")
        shutil.copyfile(root / "Cargo.lock", stage / "Cargo.lock")
        paths = capture(root, ["git", "ls-files", "-z", "src", "examples", "Cargo.toml", "scripts/generate_tutorial_assets.py"]).split("\0")
        manifest = {
            "schema_version": 1,
            "source_revision": capture(root, ["git", "rev-parse", "HEAD"]).strip(),
            "source_tree": capture(root, ["git", "rev-parse", "HEAD^{tree}"]).strip(),
            "worktree_dirty": bool(capture(root, ["git", "status", "--porcelain", "--untracked-files=normal"]).strip()),
            "source_sha256": {path: digest(root / path) for path in paths if path},
            "rustc": capture(root, ["rustc", "--version", "--verbose"]).strip(),
            "cargo": capture(root, ["cargo", "--version"]).strip(),
            "python": platform.python_version(),
            "platform": {"system": platform.system(), "machine": platform.machine()},
            "environment": {key: os.environ.get(key) for key in (
                "RUSTFLAGS", "CARGO_ENCODED_RUSTFLAGS", "CARGO_BUILD_TARGET", "RUSTUP_TOOLCHAIN")},
            "features": [], "profile": "dev", "executions": executions,
            "outputs_sha256": {path.name: digest(path) for path in sorted(stage.iterdir())},
        }
        (stage / "provenance.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        if check:
            require(output.is_dir(), "no generated tutorial assets; run generation before --check")
            old = {path.name: digest(path) for path in output.iterdir() if path.is_file()}
            new = {path.name: digest(path) for path in stage.iterdir()}
            require(old == new, "tutorial assets are stale or not reproducible; regenerate and inspect the change")
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            stage.replace(output)
    print(f"Tutorial assets {'verified by re-execution' if check else 'generated from Rust execution'}: {output}")
    print(f"Line fit: {len(line)} samples; Kalman filter: {len(kalman)} samples; 5 SVG figures.")
    print(line_text(line).strip())
    print(kalman_text(kalman).strip())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="execute again and require identical generated assets")
    args = parser.parse_args()
    try:
        generate(args.root.resolve(), args.check)
    except (OSError, ValueError, subprocess.SubprocessError) as error:
        print(f"tutorial asset generation failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
