#!/usr/bin/env python3
"""Execute the Rust tutorials, validate their exports, and render deterministic SVGs.

Only Python's standard library is needed. Numerical results, including the dense
polynomial curve, come from Rust. Validation checks consistency; it never fits
coefficients or supplies replacement values. Failed generation removes stale
assets. --check executes again and compares all generated bytes.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import html
import io
import json
import math
import os
from pathlib import Path
import platform
import shutil
import subprocess
import sys
import tempfile

POLYNOMIAL_COLUMNS = (
    "x,observed_y,reference_y,noise,fitted_y,residual,a,b,c,"
    "reference_a,reference_b,reference_c,residual_norm,sample_count"
).split(",")
CURVE_COLUMNS = "x,fitted_y,reference_y,sample_count".split(",")
KALMAN_COLUMNS = (
    "time_s,measured_m,dt_s,acceleration_variance,measurement_variance,"
    "initial_position_m,initial_velocity_m_s,initial_p00,initial_p01,initial_p10,initial_p11,"
    "predicted_position_m,predicted_velocity_m_s,predicted_p00,predicted_p01,predicted_p10,predicted_p11,"
    "position_m,velocity_m_s,p00,p01,p10,p11,innovation_m,innovation_variance,position_gain,velocity_gain,sample_count"
).split(",")
EXAMPLES = {"mapped_least_squares": POLYNOMIAL_COLUMNS, "kalman_1d": KALMAN_COLUMNS}
CURVE_FILE = "mapped_least_squares_curve.csv"


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def close(actual: float, expected: float, label: str, tolerance: float = 2e-5) -> None:
    require(math.isclose(actual, expected, rel_tol=tolerance, abs_tol=tolerance), label)


def read_csv(text: str, columns: list[str]) -> list[dict[str, float]]:
    reader = csv.DictReader(io.StringIO(text))
    require(reader.fieldnames == columns, "unexpected CSV schema (including column order)")
    rows = []
    for index, row in enumerate(reader, 1):
        require(None not in row and all(row.get(key) is not None for key in columns),
                f"malformed CSV row {index}")
        values = {key: float(row[key]) for key in columns}
        require(all(math.isfinite(value) for value in values.values()), f"non-finite row {index}")
        rows.append(values)
    require(bool(rows), "empty CSV export")
    require(all(row["sample_count"] == len(rows) for row in rows), "truncated or inconsistent sample count")
    return rows


def validate_polynomial(rows: list[dict[str, float]], curve: list[dict[str, float]]) -> None:
    require(len({r["x"] for r in rows}) >= 3, "quadratic requires at least three distinct inputs")
    first = rows[0]
    constants = ("a", "b", "c", "reference_a", "reference_b", "reference_c", "residual_norm")
    require(first["residual_norm"] >= 0, "negative residual norm")
    for row in rows:
        require(all(row[key] == first[key] for key in constants), "inconsistent polynomial metadata")
        close(row["residual"], row["observed_y"] - row["fitted_y"], "residual sign/value", 1e-10)
        close(row["observed_y"], row["reference_y"] + row["noise"], "synthetic observation", 1e-10)
    close(first["residual_norm"], math.sqrt(sum(r["residual"] ** 2 for r in rows)), "residual norm", 1e-10)
    require(len(curve) >= 3, "missing dense curve")
    xmin, xmax = min(r["x"] for r in rows), max(r["x"] for r in rows)
    close(curve[0]["x"], xmin, "curve start", 1e-10)
    close(curve[-1]["x"], xmax, "curve end", 1e-10)
    for index, row in enumerate(curve):
        close(row["x"], xmin + (xmax - xmin) * index / (len(curve) - 1), "curve grid", 1e-10)
        if index:
            require(row["x"] > curve[index - 1]["x"], "non-increasing curve grid")
    # These are validation identities, not a second fit or a rendering data source.
    for row in rows + curve:
        x = row["x"]
        close(row["fitted_y"], (first["a"] * x + first["b"]) * x + first["c"], "fitted value", 1e-10)
        close(row["reference_y"], (first["reference_a"] * x + first["reference_b"]) * x
              + first["reference_c"], "synthetic reference", 1e-10)


def validate_kalman(rows: list[dict[str, float]]) -> None:
    constants = [key for key in KALMAN_COLUMNS if key.startswith("initial_")]
    constants += ["dt_s", "acceleration_variance", "measurement_variance"]
    for index, row in enumerate(rows, 1):
        require(all(row[key] == rows[0][key] for key in constants), "changing initial conditions/settings")
        require(row["dt_s"] > 0 and row["measurement_variance"] > 0
                and row["acceleration_variance"] >= 0, "invalid uncertainty or time settings")
        close(row["time_s"], index * row["dt_s"], "sample time (first reading follows prediction)")
        close(row["innovation_m"], row["measured_m"] - row["predicted_position_m"], "innovation")
        close(row["innovation_variance"], row["predicted_p00"] + row["measurement_variance"], "innovation variance")
        require(row["innovation_variance"] > 0, "nonpositive innovation variance")
        close(row["position_gain"], row["predicted_p00"] / row["innovation_variance"], "position gain")
        close(row["velocity_gain"], row["predicted_p10"] / row["innovation_variance"], "velocity gain")
        for state, gain in (("position_m", "position_gain"), ("velocity_m_s", "velocity_gain")):
            close(row[state], row["predicted_" + state] + row[gain] * row["innovation_m"], "correction")
        for prefix in ("initial_", "predicted_", ""):
            a, b, c, d = (row[prefix + key] for key in ("p00", "p01", "p10", "p11"))
            require(a >= 0 and d >= 0, "negative covariance diagonal")
            close(b, c, "asymmetric covariance")
            require(a * d - b * c >= -2e-5 * max(1.0, abs(a * d)), "indefinite covariance")


def polynomial_text(rows: list[dict[str, float]]) -> str:
    first = rows[0]
    lines = [f"a = {first['a']:.3f}, b = {first['b']:.3f}, c = {first['c']:.3f}",
             "x observed_y fitted_y residual"]
    lines += [f"{r['x']:.3f} {r['observed_y']:.3f} {r['fitted_y']:.3f} {r['residual']:.3f}" for r in rows]
    lines.append(f"residual norm = {first['residual_norm']:.3f}")
    return "\n".join(lines) + "\n"


def kalman_text(rows: list[dict[str, float]]) -> str:
    return "time_s measured_m position_m velocity_m_s\n" + "".join(
        f"{r['time_s']:.0f} {r['measured_m']:.3f} {r['position_m']:.3f} {r['velocity_m_s']:.3f}\n"
        for r in rows
    )


class Svg:
    """Small deterministic drawing vocabulary, not a numerical framework."""
    def __init__(self, title: str, description: str):
        self.parts = [
            '<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="600" viewBox="0 0 1000 600" role="img" aria-labelledby="title desc">',
            f'<title id="title">{html.escape(title)}</title><desc id="desc">{html.escape(description)}</desc>',
            '<rect width="1000" height="600" rx="12" fill="white"/>',
            '<g font-family="system-ui, sans-serif" fill="currentColor">',
        ]
        self.text(40, 44, title, 25, weight="600")
        self.text(40, 74, description, 14)

    def text(self, x: float, y: float, text: str, size: int = 15, **attrs: str) -> None:
        extra = " ".join(f'{key}="{html.escape(str(value), quote=True)}"' for key, value in attrs.items())
        extra = extra.replace('weight=', 'font-weight=')
        self.parts.append(f'<text x="{x:.3f}" y="{y:.3f}" font-size="{size}" {extra}>{html.escape(text)}</text>')

    def line(self, x1: float, y1: float, x2: float, y2: float, width: float = 1, opacity: float = 1) -> None:
        self.parts.append(f'<path d="M{x1:.3f},{y1:.3f} L{x2:.3f},{y2:.3f}" fill="none" stroke="currentColor" stroke-width="{width}" opacity="{opacity}"/>')

    def polyline(self, points: list[tuple[float, float]], dashed: bool = False) -> None:
        positions = " ".join(f"{x:.3f},{y:.3f}" for x, y in points)
        extra = 'stroke-dasharray="7 5" opacity="0.55"' if dashed else ''
        self.parts.append(f'<polyline points="{positions}" fill="none" stroke="currentColor" stroke-width="2" {extra}/>')

    def marker(self, x: float, y: float, cross: bool = False) -> None:
        if cross:
            self.line(x - 5, y - 5, x + 5, y + 5, 2)
            self.line(x - 5, y + 5, x + 5, y - 5, 2)
        else:
            self.parts.append(f'<circle cx="{x:.3f}" cy="{y:.3f}" r="4"/>')

    def finish(self) -> str:
        self.text(40, 573, "stack-algebra / executed Rust example", 13)
        return "\n".join(self.parts + ["</g></svg>\n"])


def limits(values: list[float], zero: bool = False) -> tuple[float, float, list[float]]:
    lo, hi = min(values), max(values)
    if zero:
        lo, hi = min(lo, 0), max(hi, 0)
    span = hi - lo or max(1.0, abs(lo) * 0.2)
    lo, hi = lo - span * 0.08, hi + span * 0.08
    raw = (hi - lo) / 5
    power = 10 ** math.floor(math.log10(raw))
    step = next(n for n in (1, 2, 5, 10) if n * power >= raw) * power
    ticks = [index * step for index in range(math.ceil(lo / step), math.floor(hi / step) + 1)]
    return lo, hi, ticks


def chart(title: str, description: str, rows: list[dict[str, float]], xkey: str,
          series: list[tuple[str, str, bool]], xlabel: str, ylabel: str,
          footer: str, zero: bool = False, curve: list[dict[str, float]] | None = None) -> str:
    svg = Svg(title, description)
    datasets = [(key, label, cross, curve if curve is not None and not cross else rows)
                for key, label, cross in series]
    xmin, xmax, xticks = limits([r[xkey] for _, _, _, data in datasets for r in data])
    ymin, ymax, yticks = limits([r[key] for key, _, _, data in datasets for r in data], zero)
    px = lambda x: 100 + (x - xmin) / (xmax - xmin) * 840
    py = lambda y: 450 - (y - ymin) / (ymax - ymin) * 300
    for tick in xticks:
        x = px(tick)
        svg.line(x, 150, x, 450, opacity=0.12)
        svg.text(x, 476, f"{tick:g}", **{"text-anchor": "middle"})
    for tick in yticks:
        y = py(tick)
        svg.line(100, y, 940, y, opacity=0.12)
        svg.text(87, y + 5, f"{tick:g}", **{"text-anchor": "end"})
    svg.line(100, 150, 100, 450)
    svg.line(100, 450, 940, 450)
    svg.text(520, 508, xlabel, **{"text-anchor": "middle"})
    svg.text(100, 137, ylabel)
    if len(series) == 1 and series[0][0] == "residual":
        svg.line(100, py(0), 940, py(0), opacity=0.5)
    for index, (key, label, cross, data) in enumerate(datasets):
        legend = 110 + index * (280 if len(series) == 3 else 370)
        if curve is not None and not cross:
            svg.polyline([(legend - 8, 107), (legend + 12, 107)], key == "reference_y")
        else:
            svg.marker(legend, 107, cross)
        svg.text(legend + 19, 112, label)
        points = [(px(row[xkey]), py(row[key])) for row in data]
        if curve is not None and not cross:
            # Join Rust's dense evaluations. Do not interpolate or evaluate a model here.
            svg.parts.append(f'<g data-series="{key}">')
            svg.polyline(points, key == "reference_y")
            svg.parts.append('</g>')
        else:
            if not cross:
                ordered = sorted(points)
                for a, b in zip(ordered, ordered[1:]):
                    svg.line(*a, *b, width=2)
            for x, y in points:
                svg.marker(x, y, cross)
    svg.text(40, 544, footer, 14)
    return svg.finish()


def first_update(row: dict[str, float]) -> str:
    svg = Svg("One reading updates position and velocity",
              f"First correction at t = {row['time_s']:g} s. All three rows describe this same instant.")
    groups = [
        ("Predict", row["predicted_position_m"], row["predicted_p00"], row["predicted_velocity_m_s"]),
        ("Measure", row["measured_m"], row["measurement_variance"], None),
        ("Correct", row["position_m"], row["p00"], row["velocity_m_s"]),
    ]
    bounds = [p + sign * math.sqrt(variance) for _, p, variance, _ in groups for sign in (-1, 1)]
    lo, hi, ticks = limits(bounds)
    px = lambda x: 170 + (x - lo) / (hi - lo) * 560
    svg.text(170, 112, "Position (m): shared scale; bands show ±1 standard deviation", 14)
    for tick in ticks:
        svg.text(px(tick), 143, f"{tick:g}", 13, **{"text-anchor": "middle"})
        svg.line(px(tick), 150, px(tick), 410, opacity=0.12)
    for index, (name, position, variance, velocity) in enumerate(groups):
        y = 195 + index * 98
        sigma = math.sqrt(variance)
        svg.text(40, y + 5, name, 20, weight="600")
        svg.line(170, y, 730, y, opacity=0.2)
        svg.line(px(position - sigma), y, px(position + sigma), y, width=18, opacity=0.16)
        svg.marker(px(position), y, name == "Measure")
        svg.text(170, y + 32, f"position {position:.3f} m   /   variance {variance:.3f} m²", 14)
        svg.text(765, y + 5, "Position only" if velocity is None else f"v = {velocity:.3f} m/s", 16)
    svg.text(40, 466, f"Innovation: {row['innovation_m']:.3f} m   |   Position gain: {row['position_gain']:.6f}   |   Velocity gain: {row['velocity_gain']:.6f} 1/s", 16)
    svg.text(40, 507, f"Initial state: p = {row['initial_position_m']:g} m, v = {row['initial_velocity_m_s']:g} m/s. No velocity measurement is supplied.", 14)
    svg.text(40, 536, "Bands express the model's marginal uncertainty, not measured error or a ground-truth trajectory.", 14)
    return svg.finish()


def render(polynomial: list[dict[str, float]], kalman: list[dict[str, float]],
           curve: list[dict[str, float]]) -> dict[str, str]:
    first = polynomial[0]
    worst = max(polynomial, key=lambda r: abs(r["residual"]))
    return {
        "polynomial-fit.svg": chart("Recover a curved trend from noisy measurements",
            f"{len(polynomial)} observations, three fitted coefficients. Both curves use {len(curve)} Rust-evaluated points.",
            polynomial, "x", [("fitted_y", "Fitted quadratic", False),
            ("reference_y", "Synthetic reference", False), ("observed_y", "Observations", True)],
            "Input x", "Observed / fitted y",
            f"y = {first['a']:.3f}x² {first['b']:+.3f}x {first['c']:+.3f}   |   Residual norm: {first['residual_norm']:.3f}",
            curve=curve),
        "polynomial-residuals.svg": chart("Inspect what the quadratic does not explain",
            "Observed minus fitted. These are residuals, not the known synthetic noise samples.", polynomial, "x",
            [("residual", "Residual", True)], "Input x", "Residual in y",
            f"Largest magnitude: {worst['residual']:+.3f} at x = {worst['x']:.3f}. This is a separate residual axis.", zero=True),
        "kalman-position.svg": chart("Estimate position from imperfect readings",
            "The actual input sequence and post-correction state from kalman_1d.rs.", kalman, "time_s",
            [("position_m", "Estimated position", False), ("measured_m", "Position reading", True)], "Time (s)", "Position (m)",
            "Lines join discrete estimates. No ground-truth trajectory is supplied.", zero=True),
        "kalman-velocity.svg": chart("Infer velocity from position readings",
            "Each value is exported after a predict-and-correct step; velocity is not measured.", kalman, "time_s",
            [("velocity_m_s", "Estimated velocity", False)], "Time (s)", "Velocity (m/s)",
            f"Initial estimate: {kalman[0]['initial_velocity_m_s']:g} m/s. Final estimate: {kalman[-1]['velocity_m_s']:.3f} m/s.", zero=True),
        "kalman-first-update.svg": first_update(kalman[0]),
    }


def capture(root: Path, command: list[str]) -> str:
    print("+ " + " ".join(command), flush=True)
    return subprocess.run(command, cwd=root, check=True, text=True,
                          stdout=subprocess.PIPE, timeout=1800).stdout


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def generate(root: Path, check: bool = False) -> None:
    output = root / "docs/generated/tutorials"
    if not check and output.exists():
        shutil.rmtree(output)
    build = root / "build"
    build.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="tutorial-assets-", dir=build) as temp:
        stage = Path(temp) / "assets"
        stage.mkdir()
        if not (root / "Cargo.lock").exists():
            capture(root, ["cargo", "generate-lockfile"])
        records = {}
        executions = []
        for name, columns in EXAMPLES.items():
            command = ["cargo", "run", "--locked", "--quiet", "--no-default-features", "--example", name]
            for extension, args in (("csv", ["--", "--csv"]), ("txt", [])):
                text = capture(root, command + args)
                (stage / f"{name}.{extension}").write_text(text, encoding="utf-8")
                executions.append({"command": command + args, "exit_code": 0, "stdout": f"{name}.{extension}"})
            records[name] = read_csv((stage / f"{name}.csv").read_text(), columns)
        curve_command = ["cargo", "run", "--locked", "--quiet", "--no-default-features",
                         "--example", "mapped_least_squares", "--", "--curve-csv"]
        curve_text = capture(root, curve_command)
        (stage / CURVE_FILE).write_text(curve_text, encoding="utf-8")
        executions.append({"command": curve_command, "exit_code": 0, "stdout": CURVE_FILE})
        curve = read_csv(curve_text, CURVE_COLUMNS)
        polynomial, kalman = records["mapped_least_squares"], records["kalman_1d"]
        validate_polynomial(polynomial, curve)
        validate_kalman(kalman)
        for name, expected in (("mapped_least_squares", polynomial_text(polynomial)), ("kalman_1d", kalman_text(kalman))):
            require((stage / f"{name}.txt").read_text() == expected, f"{name}: text and CSV modes disagree")
        for filename, contents in render(polynomial, kalman, curve).items():
            (stage / filename).write_text(contents, encoding="utf-8")
        shutil.copyfile(root / "Cargo.lock", stage / "Cargo.lock")
        paths = capture(root, ["git", "ls-files", "-z", "src", "examples", "Cargo.toml", "scripts/generate_tutorial_assets.py"]).split("\0")
        manifest = {
            "schema_version": 2,
            "source_revision": capture(root, ["git", "rev-parse", "HEAD"]).strip(),
            "source_tree": capture(root, ["git", "rev-parse", "HEAD^{tree}"]).strip(),
            "worktree_dirty": bool(capture(root, ["git", "status", "--porcelain", "--untracked-files=normal"]).strip()),
            "source_sha256": {path: digest(root / path) for path in paths if path},
            "rustc": capture(root, ["rustc", "--version", "--verbose"]).strip(),
            "cargo": capture(root, ["cargo", "--version"]).strip(),
            "python": platform.python_version(),
            "platform": {"system": platform.system(), "machine": platform.machine()},
            "environment": {key: os.environ.get(key) for key in (
                "RUSTFLAGS", "CARGO_ENCODED_RUSTFLAGS", "CARGO_BUILD_TARGET", "RUSTUP_TOOLCHAIN")},
            "features": [], "profile": "dev", "executions": executions,
            "outputs_sha256": {path.name: digest(path) for path in sorted(stage.iterdir())},
        }
        (stage / "provenance.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        if check:
            require(output.is_dir(), "no generated tutorial assets; run generation before --check")
            old = {path.name: digest(path) for path in output.iterdir() if path.is_file()}
            new = {path.name: digest(path) for path in stage.iterdir()}
            require(old == new, "tutorial assets are stale or not reproducible; regenerate and inspect the change")
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            stage.replace(output)
    print(f"Tutorial assets {'verified by re-execution' if check else 'generated from Rust execution'}: {output}")
    print(f"Quadratic fit: {len(polynomial)} observations, {len(curve)} curve points; Kalman: {len(kalman)} samples; 5 SVGs.")
    print(polynomial_text(polynomial).strip())
    print(kalman_text(kalman).strip())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="execute again and require identical generated assets")
    args = parser.parse_args()
    try:
        generate(args.root.resolve(), args.check)
    except (OSError, ValueError, subprocess.SubprocessError) as error:
        print(f"tutorial asset generation failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
